Search.appendIndex(
    [
                {
            "fqsen": "\\quickRdfIo\\NQuadsParser",
            "name": "NQuadsParser",
            "summary": "Parses\u0020only\u0020n\u002Dquads\u0020and\u0020n\u002Dtriples\u0020but\u0020does\u0020it\u0020fast\u0020\u0028thanks\u0020to\u0020parsing\u0020in\u0020chunks\nand\u0020extensive\u0020use\u0020of\u0020regullar\u0020expressions\u0029.",
            "url": "classes/quickRdfIo-NQuadsParser.html"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020the\u0020parser.",
            "url": "classes/quickRdfIo-NQuadsParser.html#method___construct"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#method___destruct"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AparseStream\u0028\u0029",
            "name": "parseStream",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#method_parseStream"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#method_current"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#method_key"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#method_next"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#method_rewind"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#method_valid"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AquadGenerator\u0028\u0029",
            "name": "quadGenerator",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#method_quadGenerator"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AmakeQuad\u0028\u0029",
            "name": "makeQuad",
            "summary": "Converts\u0020regex\u0020matches\u0020array\u0020into\u0020a\u0020Quad.",
            "url": "classes/quickRdfIo-NQuadsParser.html#method_makeQuad"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AstarQuadGenerator\u0028\u0029",
            "name": "starQuadGenerator",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#method_starQuadGenerator"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AparseStar\u0028\u0029",
            "name": "parseStar",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#method_parseStar"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003Aunescape\u0028\u0029",
            "name": "unescape",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#method_unescape"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AMODE_TRIPLES",
            "name": "MODE_TRIPLES",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_MODE_TRIPLES"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AMODE_QUADS",
            "name": "MODE_QUADS",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_MODE_QUADS"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AMODE_TRIPLES_STAR",
            "name": "MODE_TRIPLES_STAR",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_MODE_TRIPLES_STAR"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AMODE_QUADS_STAR",
            "name": "MODE_QUADS_STAR",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_MODE_QUADS_STAR"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AEOL",
            "name": "EOL",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_EOL"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AUCHAR",
            "name": "UCHAR",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_UCHAR"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ACOMMENT_STRICT",
            "name": "COMMENT_STRICT",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_COMMENT_STRICT"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ACOMMENT",
            "name": "COMMENT",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_COMMENT"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ACOMMENT2_STRICT",
            "name": "COMMENT2_STRICT",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_COMMENT2_STRICT"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ACOMMENT2",
            "name": "COMMENT2",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_COMMENT2"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ALANGTAG_STRICT",
            "name": "LANGTAG_STRICT",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_LANGTAG_STRICT"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ALANGTAG",
            "name": "LANGTAG",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_LANGTAG"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AIRIREF_STRICT",
            "name": "IRIREF_STRICT",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_IRIREF_STRICT"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003AIRIREF",
            "name": "IRIREF",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_IRIREF"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ABLANKNODE1_STRICT",
            "name": "BLANKNODE1_STRICT",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_BLANKNODE1_STRICT"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ABLANKNODE2_STRICT",
            "name": "BLANKNODE2_STRICT",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_BLANKNODE2_STRICT"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ABLANKNODE3_STRICT",
            "name": "BLANKNODE3_STRICT",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_BLANKNODE3_STRICT"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ABLANKNODE4_STRICT",
            "name": "BLANKNODE4_STRICT",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_BLANKNODE4_STRICT"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ABLANKNODE",
            "name": "BLANKNODE",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_BLANKNODE"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ALITERAL_STRICT",
            "name": "LITERAL_STRICT",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_LITERAL_STRICT"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ALITERAL",
            "name": "LITERAL",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_LITERAL"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ASTAR_START",
            "name": "STAR_START",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_STAR_START"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003ASTAR_END",
            "name": "STAR_END",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#constant_STAR_END"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024unescapeMap",
            "name": "unescapeMap",
            "summary": "See\u0020https\u003A\/\/www.w3.org\/TR\/n\u002Dquads\/\u0023grammar\u002Dproduction\u002DECHAR",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_unescapeMap"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024dataFactory",
            "name": "dataFactory",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_dataFactory"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024input",
            "name": "input",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_input"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024mode",
            "name": "mode",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_mode"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024regexp",
            "name": "regexp",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_regexp"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024regexpSbjPred",
            "name": "regexpSbjPred",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_regexpSbjPred"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024regexpObjGraph",
            "name": "regexpObjGraph",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_regexpObjGraph"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024regexpPred",
            "name": "regexpPred",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_regexpPred"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024regexpGraph",
            "name": "regexpGraph",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_regexpGraph"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024regexpLineEnd",
            "name": "regexpLineEnd",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_regexpLineEnd"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024regexpCommentLine",
            "name": "regexpCommentLine",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_regexpCommentLine"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024line",
            "name": "line",
            "summary": "Input\u0020line",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_line"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024offset",
            "name": "offset",
            "summary": "Character\u0020offset\u0020within\u0020a\u0020parsed\u0020line\u0020\u0028used\u0020by\u0020the\u0020star\u0020parser\u0029",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_offset"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024level",
            "name": "level",
            "summary": "Recursion\u0020level\u0020of\u0020the\u0020start\u0020parser",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_level"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsParser\u003A\u003A\u0024quads",
            "name": "quads",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsParser.html#property_quads"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsSerializer",
            "name": "NQuadsSerializer",
            "summary": "Description\u0020of\u0020Serializer",
            "url": "classes/quickRdfIo-NQuadsSerializer.html"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsSerializer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsSerializer.html#method___construct"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsSerializer\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsSerializer.html#method_serialize"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsSerializer\u003A\u003AserializeStream\u0028\u0029",
            "name": "serializeStream",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsSerializer.html#method_serializeStream"
        },                {
            "fqsen": "\\quickRdfIo\\NQuadsSerializer\u003A\u003AserializeQuad\u0028\u0029",
            "name": "serializeQuad",
            "summary": "",
            "url": "classes/quickRdfIo-NQuadsSerializer.html#method_serializeQuad"
        },                {
            "fqsen": "\\quickRdfIo\\RdfIoException",
            "name": "RdfIoException",
            "summary": "Description\u0020of\u0020RdfException",
            "url": "classes/quickRdfIo-RdfIoException.html"
        },                {
            "fqsen": "\\quickRdfIo\\TmpStreamTrait",
            "name": "TmpStreamTrait",
            "summary": "Description\u0020of\u0020TmpStreamTrait",
            "url": "classes/quickRdfIo-TmpStreamTrait.html"
        },                {
            "fqsen": "\\quickRdfIo\\TmpStreamTrait\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/quickRdfIo-TmpStreamTrait.html#method_parse"
        },                {
            "fqsen": "\\quickRdfIo\\TmpStreamTrait\u003A\u003AcloseTmpStream\u0028\u0029",
            "name": "closeTmpStream",
            "summary": "",
            "url": "classes/quickRdfIo-TmpStreamTrait.html#method_closeTmpStream"
        },                {
            "fqsen": "\\quickRdfIo\\TmpStreamTrait\u003A\u003A\u0024tmpStream",
            "name": "tmpStream",
            "summary": "",
            "url": "classes/quickRdfIo-TmpStreamTrait.html#property_tmpStream"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser",
            "name": "TriGParser",
            "summary": "Description\u0020of\u0020Parser",
            "url": "classes/quickRdfIo-TriGParser.html"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#method___construct"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#method___destruct"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003AparseStream\u0028\u0029",
            "name": "parseStream",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#method_parseStream"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#method_current"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#method_key"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#method_next"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#method_rewind"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#method_valid"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003ACHUNK_SIZE",
            "name": "CHUNK_SIZE",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#constant_CHUNK_SIZE"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003A\u0024dataFactory",
            "name": "dataFactory",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#property_dataFactory"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#property_options"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003A\u0024parser",
            "name": "parser",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#property_parser"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003A\u0024input",
            "name": "input",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#property_input"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003A\u0024quadsBuffer",
            "name": "quadsBuffer",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#property_quadsBuffer"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003A\u0024n",
            "name": "n",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#property_n"
        },                {
            "fqsen": "\\quickRdfIo\\TriGParser\u003A\u003A\u0024prefixCallback",
            "name": "prefixCallback",
            "summary": "",
            "url": "classes/quickRdfIo-TriGParser.html#property_prefixCallback"
        },                {
            "fqsen": "\\quickRdfIo\\TurtleSerializer",
            "name": "TurtleSerializer",
            "summary": "Description\u0020of\u0020TurtleSerializer",
            "url": "classes/quickRdfIo-TurtleSerializer.html"
        },                {
            "fqsen": "\\quickRdfIo\\TurtleSerializer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/quickRdfIo-TurtleSerializer.html#method___construct"
        },                {
            "fqsen": "\\quickRdfIo\\TurtleSerializer\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/quickRdfIo-TurtleSerializer.html#method_serialize"
        },                {
            "fqsen": "\\quickRdfIo\\TurtleSerializer\u003A\u003AserializeStream\u0028\u0029",
            "name": "serializeStream",
            "summary": "",
            "url": "classes/quickRdfIo-TurtleSerializer.html#method_serializeStream"
        },                {
            "fqsen": "\\rdfHelpers\\DefaultGraph",
            "name": "DefaultGraph",
            "summary": "Description\u0020of\u0020DefaultGraph",
            "url": "classes/rdfHelpers-DefaultGraph.html"
        },                {
            "fqsen": "\\rdfHelpers\\DefaultGraph\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfHelpers-DefaultGraph.html#method___construct"
        },                {
            "fqsen": "\\rdfHelpers\\DefaultGraph\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfHelpers-DefaultGraph.html#method___toString"
        },                {
            "fqsen": "\\rdfHelpers\\DefaultGraph\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/rdfHelpers-DefaultGraph.html#method_getValue"
        },                {
            "fqsen": "\\rdfHelpers\\DefaultGraph\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfHelpers-DefaultGraph.html#method_equals"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator",
            "name": "GenericQuadIterator",
            "summary": "Wrapper\u0020making\u0020almost\u0020anything\u0020\u0028e.g.\u0020array,\u0020generator\u0020or\u0020a\u0020single\u0020Quad\u0020object\u0029\na\u0020QuadIterator.",
            "url": "classes/rdfHelpers-GenericQuadIterator.html"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#method___construct"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#method_current"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#method_key"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#method_next"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#method_rewind"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#method_valid"
        },                {
            "fqsen": "\\rdfHelpers\\GenericQuadIterator\u003A\u003A\u0024iter",
            "name": "iter",
            "summary": "",
            "url": "classes/rdfHelpers-GenericQuadIterator.html#property_iter"
        },                {
            "fqsen": "\\rdfHelpers\\GenericTermIterator",
            "name": "GenericTermIterator",
            "summary": "Wrapper\u0020making\u0020almost\u0020anything\u0020\u0028e.g.\u0020array,\u0020generator\u0020or\u0020a\u0020single\u0020Quad\u0020object\u0029\na\u0020QuadIterator.",
            "url": "classes/rdfHelpers-GenericTermIterator.html"
        },                {
            "fqsen": "\\rdfHelpers\\GenericTermIterator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfHelpers-GenericTermIterator.html#method___construct"
        },                {
            "fqsen": "\\rdfHelpers\\GenericTermIterator\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfHelpers-GenericTermIterator.html#method_current"
        },                {
            "fqsen": "\\rdfHelpers\\GenericTermIterator\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/rdfHelpers-GenericTermIterator.html#method_key"
        },                {
            "fqsen": "\\rdfHelpers\\GenericTermIterator\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/rdfHelpers-GenericTermIterator.html#method_next"
        },                {
            "fqsen": "\\rdfHelpers\\GenericTermIterator\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/rdfHelpers-GenericTermIterator.html#method_rewind"
        },                {
            "fqsen": "\\rdfHelpers\\GenericTermIterator\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/rdfHelpers-GenericTermIterator.html#method_valid"
        },                {
            "fqsen": "\\rdfHelpers\\GenericTermIterator\u003A\u003A\u0024iter",
            "name": "iter",
            "summary": "",
            "url": "classes/rdfHelpers-GenericTermIterator.html#property_iter"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil",
            "name": "NtriplesUtil",
            "summary": "Description\u0020of\u0020Util",
            "url": "classes/rdfHelpers-NtriplesUtil.html"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003AescapeLiteral\u0028\u0029",
            "name": "escapeLiteral",
            "summary": "",
            "url": "classes/rdfHelpers-NtriplesUtil.html#method_escapeLiteral"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003AescapeIri\u0028\u0029",
            "name": "escapeIri",
            "summary": "",
            "url": "classes/rdfHelpers-NtriplesUtil.html#method_escapeIri"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003AserializeIri\u0028\u0029",
            "name": "serializeIri",
            "summary": "",
            "url": "classes/rdfHelpers-NtriplesUtil.html#method_serializeIri"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003AserializeLiteral\u0028\u0029",
            "name": "serializeLiteral",
            "summary": "",
            "url": "classes/rdfHelpers-NtriplesUtil.html#method_serializeLiteral"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003AserializeQuad\u0028\u0029",
            "name": "serializeQuad",
            "summary": "",
            "url": "classes/rdfHelpers-NtriplesUtil.html#method_serializeQuad"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/rdfHelpers-NtriplesUtil.html#method_serialize"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003A\u0024iriEscapeMap",
            "name": "iriEscapeMap",
            "summary": "Characters\u0020forbidden\u0020in\u0020n\u002Dtriples\u0020literals\u0020according\u0020to\nhttps\u003A\/\/www.w3.org\/TR\/n\u002Dtriples\/\u0023grammar\u002Dproduction\u002DIRIREF",
            "url": "classes/rdfHelpers-NtriplesUtil.html#property_iriEscapeMap"
        },                {
            "fqsen": "\\rdfHelpers\\NtriplesUtil\u003A\u003A\u0024literalEscapeMap",
            "name": "literalEscapeMap",
            "summary": "Characters\u0020forbidden\u0020in\u0020n\u002Dtriples\u0020literals\u0020according\u0020to\nhttps\u003A\/\/www.w3.org\/TR\/n\u002Dtriples\/\u0023grammar\u002Dproduction\u002DSTRING_LITERAL_QUOTE",
            "url": "classes/rdfHelpers-NtriplesUtil.html#property_literalEscapeMap"
        },                {
            "fqsen": "\\rdfHelpers\\RdfHelpersException",
            "name": "RdfHelpersException",
            "summary": "Description\u0020of\u0020RdfHelpersException",
            "url": "classes/rdfHelpers-RdfHelpersException.html"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace",
            "name": "RdfNamespace",
            "summary": "Provides\u0020an\u0020implementation\u0020of\u0020rdfInterface\\RdfNamespace.",
            "url": "classes/rdfHelpers-RdfNamespace.html"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003AgetNamedNode\u0028\u0029",
            "name": "getNamedNode",
            "summary": "",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_getNamedNode"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Registers\u0020a\u0020given\u0020URL\u0020prefix.",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_add"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Drops\u0020a\u0020given\u0020short\u0020name\u0020and\u0020IRI\u0020prefix\u0020associated\u0020with\u0020it.",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_remove"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Returns\u0020a\u0020IRI\u0020prefix\u0020for\u0020a\u0020given\u0020short\u0020name.",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_get"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Returns\u0020associative\u0020array\u0020of\u0020all\u0020registered\u0020namespaces\u0020with\u0020array\u0020keys\nbeing\u0020namespace\u0020short\u0020names\u0020and\u0020array\u0020values\u0020containing\u0020URL\u0020prefixes.",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_getAll"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003Aexpand\u0028\u0029",
            "name": "expand",
            "summary": "Expands\u0020a\u0020shortened\u0020IRI\u0020to\u0020a\u0020NamedNode.",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_expand"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003Ashorten\u0028\u0029",
            "name": "shorten",
            "summary": "Shortens\u0020provided\u0020NamedNode\u0020IRI.",
            "url": "classes/rdfHelpers-RdfNamespace.html#method_shorten"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003A\u0024n",
            "name": "n",
            "summary": "",
            "url": "classes/rdfHelpers-RdfNamespace.html#property_n"
        },                {
            "fqsen": "\\rdfHelpers\\RdfNamespace\u003A\u003A\u0024namespaces",
            "name": "namespaces",
            "summary": "",
            "url": "classes/rdfHelpers-RdfNamespace.html#property_namespaces"
        },                {
            "fqsen": "\\rdfInterface\\BlankNode",
            "name": "BlankNode",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-BlankNode.html"
        },                {
            "fqsen": "\\rdfInterface\\BlankNode\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-BlankNode.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory",
            "name": "DataFactory",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AnamedNode\u0028\u0029",
            "name": "namedNode",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_namedNode"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AblankNode\u0028\u0029",
            "name": "blankNode",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_blankNode"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003Aliteral\u0028\u0029",
            "name": "literal",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_literal"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AdefaultGraph\u0028\u0029",
            "name": "defaultGraph",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_defaultGraph"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003Aquad\u0028\u0029",
            "name": "quad",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_quad"
        },                {
            "fqsen": "\\rdfInterface\\Dataset",
            "name": "Dataset",
            "summary": "Main,\u0020edge\u0028quad\u0029\u0020and\u0020Dataset\u002Doriented\u0020Dataset\u0020API",
            "url": "classes/rdfInterface-Dataset.html"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Acopy\u0028\u0029",
            "name": "copy",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_copy"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AcopyExcept\u0028\u0029",
            "name": "copyExcept",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_copyExcept"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Aunion\u0028\u0029",
            "name": "union",
            "summary": "Returns\u0020a\u0020new\u0020dataset\u0020being\u0020a\u0020union\u0020of\u0020the\u0020current\u0020one\u0020and\u0020the\u0020\u0024other\u0020one.",
            "url": "classes/rdfInterface-Dataset.html#method_union"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Axor\u0028\u0029",
            "name": "xor",
            "summary": "Returns\u0020a\u0020dataset\u0020being\u0020a\u0020symmetric\u0020difference\u0020of\u0020the\u0020current\u0020dataset\u0020and\nthe\u0020\u0024other\u0020one.",
            "url": "classes/rdfInterface-Dataset.html#method_xor"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020quad\u0028s\u0029\u0020to\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "In\u002Dplace\u0020removes\u0020quads\u0020from\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_delete"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AdeleteExcept\u0028\u0029",
            "name": "deleteExcept",
            "summary": "In\u002Dplace\u0020removes\u0020quads\u0020from\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_deleteExcept"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AforEach\u0028\u0029",
            "name": "forEach",
            "summary": "Iterates\u0020trough\u0020all\u0020quads\u0020replacing\u0020them\u0020with\u0020a\u0020callback\u0020result.",
            "url": "classes/rdfInterface-Dataset.html#method_forEach"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "Checks\u0020if\u0020a\u0020given\u0020offset\u0020exists.",
            "url": "classes/rdfInterface-Dataset.html#method_offsetExists"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "Returns\u0020a\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-Dataset.html#method_offsetGet"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "Assigns\u0020a\u0020new\u0020value\u0020to\u0020the\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-Dataset.html#method_offsetSet"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "Removes\u0020a\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-Dataset.html#method_offsetUnset"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "Returns\u0020the\u0020current\u0020quad.",
            "url": "classes/rdfInterface-Dataset.html#method_current"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare",
            "name": "DatasetCompare",
            "summary": "Main,\u0020edge\u0028quad\u0029\u0020and\u0020Dataset\u002Doriented\u0020Dataset\u0020API",
            "url": "classes/rdfInterface-DatasetCompare.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare\u003A\u003Aevery\u0028\u0029",
            "name": "every",
            "summary": "",
            "url": "classes/rdfInterface-DatasetCompare.html#method_every"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare\u003A\u003Anone\u0028\u0029",
            "name": "none",
            "summary": "",
            "url": "classes/rdfInterface-DatasetCompare.html#method_none"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare\u003A\u003Aany\u0028\u0029",
            "name": "any",
            "summary": "",
            "url": "classes/rdfInterface-DatasetCompare.html#method_any"
        },                {
            "fqsen": "\\rdfInterface\\DatasetListQuadParts",
            "name": "DatasetListQuadParts",
            "summary": "Set\u0020of\u0020methods\u0020for\u0020listing\u0020distinct\u0020Terms\u0020being\u0020used\u0020on\u0020a\u0020given\u0020position\nof\u0020dataset\u0020quads.",
            "url": "classes/rdfInterface-DatasetListQuadParts.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetListQuadParts\u003A\u003AlistSubjects\u0028\u0029",
            "name": "listSubjects",
            "summary": "",
            "url": "classes/rdfInterface-DatasetListQuadParts.html#method_listSubjects"
        },                {
            "fqsen": "\\rdfInterface\\DatasetListQuadParts\u003A\u003AlistPredicates\u0028\u0029",
            "name": "listPredicates",
            "summary": "",
            "url": "classes/rdfInterface-DatasetListQuadParts.html#method_listPredicates"
        },                {
            "fqsen": "\\rdfInterface\\DatasetListQuadParts\u003A\u003AlistObjects\u0028\u0029",
            "name": "listObjects",
            "summary": "",
            "url": "classes/rdfInterface-DatasetListQuadParts.html#method_listObjects"
        },                {
            "fqsen": "\\rdfInterface\\DatasetListQuadParts\u003A\u003AlistGraphs\u0028\u0029",
            "name": "listGraphs",
            "summary": "",
            "url": "classes/rdfInterface-DatasetListQuadParts.html#method_listGraphs"
        },                {
            "fqsen": "\\rdfInterface\\DatasetMapReduce",
            "name": "DatasetMapReduce",
            "summary": "Immutable\u0020edge\u0020processing\u0020methods",
            "url": "classes/rdfInterface-DatasetMapReduce.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetMapReduce\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "",
            "url": "classes/rdfInterface-DatasetMapReduce.html#method_map"
        },                {
            "fqsen": "\\rdfInterface\\DatasetMapReduce\u003A\u003Areduce\u0028\u0029",
            "name": "reduce",
            "summary": "",
            "url": "classes/rdfInterface-DatasetMapReduce.html#method_reduce"
        },                {
            "fqsen": "\\rdfInterface\\DefaultGraph",
            "name": "DefaultGraph",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-DefaultGraph.html"
        },                {
            "fqsen": "\\rdfInterface\\DefaultGraph\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-DefaultGraph.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Literal",
            "name": "Literal",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-Literal.html"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020a\u0020new\u0020literal.",
            "url": "classes/rdfInterface-Literal.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Returns\u0020literal\u0027s\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_getValue"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AgetLang\u0028\u0029",
            "name": "getLang",
            "summary": "Returns\u0020literal\u0027s\u0020language\u0020tag.",
            "url": "classes/rdfInterface-Literal.html#method_getLang"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AgetDatatype\u0028\u0029",
            "name": "getDatatype",
            "summary": "Returns\u0020literal\u0027s\u0020datatype.",
            "url": "classes/rdfInterface-Literal.html#method_getDatatype"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AwithValue\u0028\u0029",
            "name": "withValue",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020given\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_withValue"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AwithLang\u0028\u0029",
            "name": "withLang",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020lang\u0020tag\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_withLang"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AwithDatatype\u0028\u0029",
            "name": "withDatatype",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020with\u0020this\u0020one\u0020with\u0020datatype\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_withDatatype"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003ACAST_LEXICAL_FORM",
            "name": "CAST_LEXICAL_FORM",
            "summary": "",
            "url": "classes/rdfInterface-Literal.html#constant_CAST_LEXICAL_FORM"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003ACAST_DATATYPE",
            "name": "CAST_DATATYPE",
            "summary": "",
            "url": "classes/rdfInterface-Literal.html#constant_CAST_DATATYPE"
        },                {
            "fqsen": "\\rdfInterface\\NamedNode",
            "name": "NamedNode",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-NamedNode.html"
        },                {
            "fqsen": "\\rdfInterface\\NamedNode\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-NamedNode.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Parser",
            "name": "Parser",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html"
        },                {
            "fqsen": "\\rdfInterface\\Parser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Parser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html#method_parse"
        },                {
            "fqsen": "\\rdfInterface\\Parser\u003A\u003AparseStream\u0028\u0029",
            "name": "parseStream",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html#method_parseStream"
        },                {
            "fqsen": "\\rdfInterface\\Quad",
            "name": "Quad",
            "summary": "Extends\u0020Term\u0020because\u0020of\u0020RDF\u002A",
            "url": "classes/rdfInterface-Quad.html"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "Null\u0020is\u0020not\u0020allowed\u0020to\u0020deal\u0020with\u0020the\u0020ambiguity\u0020between\u0020DefaultGraph\u0020and\nnull\u0020which\u0020mean\u0020the\u0020same\u0020\u0028although\u0020it\u0020should\u0020be\u0020noted\u0020that\u0020all\u0020quads\u0020in\nNamedNode\/BlankNode\u0020graphs\u0020also\u0020belong\u0020to\u0020the\u0020DefaultGraph\u0029.",
            "url": "classes/rdfInterface-Quad.html#method_getGraph"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithSubject\u0028\u0029",
            "name": "withSubject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withSubject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithPredicate\u0028\u0029",
            "name": "withPredicate",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withPredicate"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithObject\u0028\u0029",
            "name": "withObject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withObject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithGraph\u0028\u0029",
            "name": "withGraph",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withGraph"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare",
            "name": "QuadCompare",
            "summary": "Interface\u0020allowing\u0020to\u0020compare\u0020Quads.",
            "url": "classes/rdfInterface-QuadCompare.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method_getGraph"
        },                {
            "fqsen": "\\rdfInterface\\QuadIterator",
            "name": "QuadIterator",
            "summary": "",
            "url": "classes/rdfInterface-QuadIterator.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadIterator\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfInterface-QuadIterator.html#method_current"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace",
            "name": "RdfNamespace",
            "summary": "",
            "url": "classes/rdfInterface-RdfNamespace.html"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Registers\u0020a\u0020given\u0020URL\u0020prefix.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Drops\u0020a\u0020given\u0020short\u0020name\u0020and\u0020IRI\u0020prefix\u0020associated\u0020with\u0020it.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_remove"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Returns\u0020a\u0020IRI\u0020prefix\u0020for\u0020a\u0020given\u0020short\u0020name.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_get"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Returns\u0020associative\u0020array\u0020of\u0020all\u0020registered\u0020namespaces\u0020with\u0020array\u0020keys\nbeing\u0020namespace\u0020short\u0020names\u0020and\u0020array\u0020values\u0020containing\u0020URL\u0020prefixes.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_getAll"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aexpand\u0028\u0029",
            "name": "expand",
            "summary": "Expands\u0020a\u0020shortened\u0020IRI\u0020to\u0020a\u0020NamedNode.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_expand"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Ashorten\u0028\u0029",
            "name": "shorten",
            "summary": "Shortens\u0020provided\u0020NamedNode\u0020IRI.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_shorten"
        },                {
            "fqsen": "\\rdfInterface\\Serializer",
            "name": "Serializer",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html"
        },                {
            "fqsen": "\\rdfInterface\\Serializer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Serializer\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html#method_serialize"
        },                {
            "fqsen": "\\rdfInterface\\Serializer\u003A\u003AserializeStream\u0028\u0029",
            "name": "serializeStream",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html#method_serializeStream"
        },                {
            "fqsen": "\\rdfInterface\\Term",
            "name": "Term",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-Term.html"
        },                {
            "fqsen": "\\rdfInterface\\Term\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-Term.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\Term\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/rdfInterface-Term.html#method_getValue"
        },                {
            "fqsen": "\\rdfInterface\\Term\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-Term.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\TermCompare",
            "name": "TermCompare",
            "summary": "Description\u0020of\u0020TermCompare",
            "url": "classes/rdfInterface-TermCompare.html"
        },                {
            "fqsen": "\\rdfInterface\\TermCompare\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-TermCompare.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\TermCompare\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-TermCompare.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\TermIterator",
            "name": "TermIterator",
            "summary": "",
            "url": "classes/rdfInterface-TermIterator.html"
        },                {
            "fqsen": "\\rdfInterface\\TermIterator\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfInterface-TermIterator.html#method_current"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\quickRdfIo",
            "name": "quickRdfIo",
            "summary": "",
            "url": "namespaces/quickrdfio.html"
        },                {
            "fqsen": "\\rdfHelpers",
            "name": "rdfHelpers",
            "summary": "",
            "url": "namespaces/rdfhelpers.html"
        },                {
            "fqsen": "\\rdfInterface",
            "name": "rdfInterface",
            "summary": "",
            "url": "namespaces/rdfinterface.html"
        }            ]
);
